# Generated by Django 3.2.8 on 2021-10-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=16)),
                ('confirm_password', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
