# Generated by Django 3.2.7 on 2021-10-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0010_auto_20211007_1006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestInfo',
            new_name='RestInform',
        ),
    ]
